import { useId, useState } from "react";
import { useForm } from "react-hook-form";
import { useNavigate } from "react-router-dom";
import { motion } from "framer-motion";
import toast from "react-hot-toast";
import { BriefcaseBusiness, Check, ChevronDown, CircleDollarSign, Lightbulb, Rocket, Search, UsersRound } from "lucide-react";
import Input from "../components/ui/Input.jsx";
import Textarea from "../components/ui/Textarea.jsx";
import Button from "../components/ui/Button.jsx";
import simulationService from "../services/simulationService.js";

const industries = ["Artificial Intelligence", "SaaS", "FinTech", "EdTech", "HealthTech", "E-commerce", "Cybersecurity", "FoodTech", "AgriTech", "Logistics", "TravelTech", "Real Estate", "Gaming", "ClimateTech", "Robotics", "IoT", "Blockchain", "Manufacturing", "Social Media", "Other"];
const textFields = [["startupName", "Startup Name", "Example: FitAI", Input, Lightbulb], ["problem", "Problem", "Describe the problem your startup solves.", Textarea, BriefcaseBusiness], ["solution", "Solution", "Explain how your product solves this problem.", Textarea, Lightbulb], ["targetAudience", "Target Audience", "Example: College students, SMBs, Fitness enthusiasts", Textarea, UsersRound], ["businessModel", "Business Model", "Example: SaaS subscription, Marketplace, Freemium", Input, BriefcaseBusiness], ["revenueModel", "Revenue Model", "Example: Monthly subscriptions, Commission, Ads", Textarea, CircleDollarSign], ["fundingRequired", "Funding Required", "Example: $100,000 Seed Funding", Input, CircleDollarSign], ["competitors", "Competitors", "Example: Zomato, Swiggy, Uber Eats", Textarea, UsersRound], ["usp", "Unique Selling Proposition (USP)", "What makes your startup unique?", Textarea, Lightbulb], ["technologyStack", "Technology Stack", "Example: React, Node.js, MongoDB, OpenAI API", Textarea, BriefcaseBusiness], ["vision", "Vision", "Describe your long-term vision.", Textarea, Rocket]];

function FieldLabel({ children }) { return <span>{children} <span className="text-red-500" aria-hidden="true">*</span></span>; }

function IndustrySelect({ register, setValue, error }) {
  const uid = useId();
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState("");
  const filteredIndustries = industries.filter((industry) => industry.toLowerCase().includes(query.toLowerCase()));
  const selectIndustry = (industry) => { setSelected(industry); setValue("industry", industry, { shouldValidate: true }); setOpen(false); setQuery(""); };
  return <div className="sm:col-span-2"><label className="mb-1.5 block text-sm font-medium text-slate-700" htmlFor={`${uid}-search`}><FieldLabel>Industry</FieldLabel></label><input type="hidden" {...register("industry", { required: "Industry is required" })} /><div className={`relative rounded-xl border bg-white transition focus-within:border-primary-500 focus-within:ring-2 focus-within:ring-primary-100 ${error ? "border-red-400" : "border-slate-300"}`}><button type="button" onClick={() => setOpen((value) => !value)} aria-expanded={open} aria-controls={`${uid}-options`} className="flex w-full items-center justify-between gap-3 px-4 py-2.5 text-left text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-500 focus-visible:ring-inset"><span className={selected ? "text-slate-800" : "text-slate-400"}>{selected || "Example: HealthTech, FinTech, EdTech"}</span><ChevronDown size={18} className={`shrink-0 text-slate-500 transition-transform ${open ? "rotate-180" : ""}`} aria-hidden="true" /></button>{open && <div id={`${uid}-options`} role="listbox" aria-label="Industry options" className="absolute z-20 mt-2 w-full overflow-hidden rounded-xl border border-slate-200 bg-white p-2 shadow-soft"><label className="relative mb-2 block"><Search size={16} className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" aria-hidden="true" /><span className="sr-only">Search industries</span><input id={`${uid}-search`} value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search industries" className="w-full rounded-lg border border-slate-200 py-2 pl-9 pr-3 text-sm outline-none transition focus:border-primary-500 focus:ring-2 focus:ring-primary-100" autoFocus /></label><div className="max-h-52 overflow-y-auto">{filteredIndustries.map((industry) => <button key={industry} type="button" role="option" aria-selected={selected === industry} onClick={() => selectIndustry(industry)} className="flex w-full items-center justify-between rounded-lg px-3 py-2.5 text-left text-sm text-slate-700 transition hover:bg-primary-50 focus-visible:bg-primary-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-500">{industry}{selected === industry && <Check size={16} className="text-primary-600" aria-hidden="true" />}</button>)}{!filteredIndustries.length && <p className="px-3 py-4 text-sm text-slate-500">No industries found.</p>}</div></div>}</div>{error && <p role="alert" className="mt-1.5 text-xs font-medium text-red-600">{error.message}</p>}</div>;
}

export default function NewSimulationPage() {
  const { register, setValue, handleSubmit, formState: { errors } } = useForm();
  const [loading, setLoading] = useState(false);
  const navigate = useNavigate();
  const submit = async (data) => { setLoading(true); try { const idea = [`Solution: ${data.solution.trim()}`, `Revenue Model: ${data.revenueModel.trim()}`, `Competitors: ${data.competitors.trim()}`, `Technology Stack: ${data.technologyStack.trim()}`, `Vision: ${data.vision.trim()}`].join("\n\n"); const response = await simulationService.createSimulation({ startupName: data.startupName, idea, industry: data.industry, targetAudience: data.targetAudience, businessModel: data.businessModel, pricing: data.fundingRequired, problemStatement: data.problem, uniqueSellingProposition: data.usp }); toast.success("Simulation completed successfully!"); navigate(`/simulations/${response.data._id}`); } catch (error) { toast.error(!error?.response ? "Network error. Please check your connection." : error.response.data?.errors?.[0]?.message || error.response.data?.message || "Failed to run simulation. Please try again."); } finally { setLoading(false); } };
  return <div className="mx-auto w-full max-w-4xl pb-4"><div className="mb-7 max-w-2xl"><p className="mb-2 text-xs font-semibold uppercase tracking-[0.16em] text-primary-600">Startup evaluation</p><h1 className="text-3xl font-bold tracking-tight text-slate-950 dark:text-white">Create a simulation</h1><p className="mt-2 text-sm leading-6 text-slate-500">Give the AI enough context to produce a practical, investor-style assessment of your venture.</p></div><motion.form initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} onSubmit={handleSubmit(submit)} noValidate className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-card dark:border-slate-700"><div className="border-b border-slate-100 px-5 py-4 dark:border-slate-700 sm:px-7"><p className="font-semibold text-slate-900 dark:text-white">Business idea</p><p className="mt-1 text-sm text-slate-500">Start with the essentials. Every field helps strengthen the analysis.</p></div><div className="space-y-7 p-5 sm:p-7"><section className="grid gap-5 sm:grid-cols-2"><div className="sm:col-span-2"><Input icon={Lightbulb} label={<FieldLabel>Startup Name</FieldLabel>} helperText="Use the name you want to evaluate." placeholder="Example: FitAI" error={errors.startupName?.message} aria-invalid={!!errors.startupName} registration={register("startupName", { required: "Startup Name is required" })} /></div><IndustrySelect register={register} setValue={setValue} error={errors.industry} /></section><div className="border-t border-slate-100 pt-7 dark:border-slate-700"><p className="mb-1 font-semibold text-slate-900 dark:text-white">Business details</p><p className="mb-5 text-sm text-slate-500">Describe the customer, problem, operating model, and ambition.</p><div className="grid gap-5 sm:grid-cols-2">{textFields.slice(1).map(([name, label, placeholder, Component, Icon]) => <div key={name} className={Component === Textarea ? "sm:col-span-2" : ""}><Component icon={Component === Input ? Icon : undefined} label={<FieldLabel>{label}</FieldLabel>} placeholder={placeholder} rows={4} helperText={Component === Input ? placeholder : undefined} error={errors[name]?.message} aria-invalid={!!errors[name]} registration={register(name, { required: `${label} is required` })} /></div>)}</div></div><div className="border-t border-slate-100 pt-6 dark:border-slate-700"><Button type="submit" fullWidth loading={loading} className="min-h-12 shadow-sm hover:shadow-md"><Rocket size={18} />{loading ? "Running AI Simulation…" : "Run AI Simulation"}</Button><p className="mt-3 text-center text-xs text-slate-500">Your startup data is used only to generate this simulation.</p></div></div></motion.form></div>;
}
